// /pages/api/seed-pi-data.js — ONE-TIME seed script. DELETE AFTER USE.
import { getSupabaseServer } from "../../utils/supabaseClient";

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "POST only" });

  // Simple secret check
  const { secret } = req.body;
  if (secret !== "seed2026ipm") return res.status(403).json({ error: "Bad secret" });

  const supabase = getSupabaseServer();
  const results = { questions: 0, sessions: 0, experts: 0, errors: [] };

  // ── QUESTIONS ──
  const questions = [
    { category: 'SOP', question_text: 'Walk us through your SOP. What is the central theme?', model_answer: 'Pick the ONE core thread that connects your intro, why-MBA, and career goals. Don\'t just summarize — highlight the "red thread." E.g., "My SOP is built around the idea that exposure to diverse perspectives drives better decisions — which is why I want IPM\'s 5-year integrated structure."', difficulty: 'medium', sort_order: 1 },
    { category: 'SOP', question_text: 'You mentioned [specific strength] in your SOP. Give me a concrete example where this strength was tested.', model_answer: 'Use the STAR method: Situation → Task → Action → Result. Be specific with numbers and outcomes. If you wrote "leadership," don\'t just say "I led my team" — say "I led a 12-member debate team, increased participation by 40%, and we reached nationals for the first time in 5 years."', difficulty: 'hard', sort_order: 2 },
    { category: 'SOP', question_text: 'Your SOP says you want to be [career goal]. What specifically will you do in Year 1 vs Year 5 vs Year 10?', model_answer: 'Show a clear progression. Year 1: Learn fundamentals, get exposure. Year 5: Mid-level role with specific responsibilities. Year 10: Leadership role or entrepreneurship. Be realistic — don\'t say "CEO of Google" but also don\'t be vague. Connect each stage back to skills IPM will give you.', difficulty: 'hard', sort_order: 3 },
    { category: 'SOP', question_text: 'If we reject your SOP and ask you to rewrite it in 5 minutes, what would you change?', model_answer: 'This tests self-awareness. Acknowledge one genuine weakness (e.g., "I\'d add more specific data to support my claims" or "I\'d make my career goal more concrete"). Never say "nothing" — that shows lack of reflection.', difficulty: 'hard', sort_order: 4 },
    { category: 'SOP', question_text: 'You wrote that IIM Indore is your dream college. What if you also get IIM Rohtak or NALSAR?', model_answer: 'Show you\'ve researched IIM Indore specifically — mention the 5-year integrated structure, Indore campus, specific clubs/fests, faculty, or alumni you\'ve looked up. Then honestly discuss how you\'d decide, showing mature thinking.', difficulty: 'medium', sort_order: 5 },
    { category: 'SOP', question_text: 'What is the biggest risk in your career plan?', model_answer: 'Show you\'ve thought about what could go wrong. E.g., "The consulting industry is evolving with AI — my risk is that traditional strategy roles may shrink. That\'s why I want to combine management with tech skills during IPM." Shows maturity.', difficulty: 'medium', sort_order: 6 },
    { category: 'SOP', question_text: 'Your SOP mentions [extracurricular]. What did you learn from it that is NOT obvious?', model_answer: 'Go beyond surface learning. If you played cricket, don\'t just say "teamwork." Say "I learned that the best captain isn\'t the best player — it\'s the one who makes others perform. I once dropped our top batsman from a match because his attitude was toxic, and we still won."', difficulty: 'medium', sort_order: 7 },
    { category: 'SOP', question_text: 'Tell me something about yourself that is NOT in your SOP or application.', model_answer: 'This is a gift question — use it to show personality. Share something interesting: a hobby, a belief, a childhood story, a skill. Make it memorable. "I collect vintage maps" is better than "I\'m hardworking."', difficulty: 'easy', sort_order: 8 },
    { category: 'Academics', question_text: 'Why did your score drop/improve between Class 10 and Class 12?', model_answer: 'Be honest. If it dropped: acknowledge it, explain what happened (e.g., health, new subjects, overconfidence), and what you learned. If it improved: explain what changed in your approach. Never blame teachers or the system — take ownership.', difficulty: 'medium', sort_order: 9 },
    { category: 'Academics', question_text: 'What is your favorite subject and why? Teach me something from it in 2 minutes.', model_answer: 'Pick a subject you genuinely enjoy. Then TEACH — don\'t just describe. E.g., "I love Economics. Let me explain the paradox of thrift: when everyone saves more during a recession, total savings actually decrease because spending drops, businesses suffer, and incomes fall."', difficulty: 'medium', sort_order: 10 },
    { category: 'Academics', question_text: 'You scored X in IPMAT. What was your preparation strategy?', model_answer: 'Be specific: how many months, daily routine, resources used, weak areas, mock test scores, what you\'d do differently. Shows discipline and self-awareness.', difficulty: 'easy', sort_order: 11 },
    { category: 'Academics', question_text: 'If you could remove one subject from your school curriculum, which one and why?', model_answer: 'This tests critical thinking, not the "right" answer. Pick any subject and build a logical argument. E.g., "I\'d restructure Social Studies to include financial literacy — knowing about the Mughal empire is useful but knowing about compound interest and taxes is immediately practical."', difficulty: 'medium', sort_order: 12 },
    { category: 'Academics', question_text: 'Explain a concept from Mathematics/Physics that has a real-world application most people don\'t know about.', model_answer: 'Show depth. E.g., "Game Theory from Math is used by telecom companies to decide pricing — if Jio drops prices, Airtel has to decide whether to match or differentiate. The Nash Equilibrium explains why they often end up at similar prices."', difficulty: 'hard', sort_order: 13 },
    { category: 'Academics', question_text: 'Why MBA at 18? Why not engineering or CA?', model_answer: 'Don\'t trash other careers. Instead, explain what specifically draws you to management: decision-making, working across functions, building organizations. Connect to a personal experience that made you realize this. "After organizing my school fest and managing a ₹2L budget across 8 events, I realized I\'m energized by coordination and strategy, not deep technical work."', difficulty: 'hard', sort_order: 14 },
    { category: 'GK', question_text: 'What is the current GDP growth rate of India? Is it good or bad?', model_answer: 'State the number (check latest RBI/IMF data). Then analyze: compare with last year, compare with China/US, discuss what\'s driving it (consumption, investment, govt spending). Show you can think beyond the number.', difficulty: 'medium', sort_order: 15 },
    { category: 'GK', question_text: 'Explain the Union Budget in 3 sentences. What was the most important announcement?', model_answer: 'Keep it crisp. Cover: total expenditure, fiscal deficit target, and 1-2 key announcements relevant to education/youth (like changes in income tax slabs or education spending). Show you actually read it, not just headlines.', difficulty: 'hard', sort_order: 16 },
    { category: 'GK', question_text: 'Should India have a Uniform Civil Code? Give arguments for and against.', model_answer: 'This tests balanced thinking. FOR: equality, simplification, gender justice. AGAINST: diversity, federalism, religious freedom. Then state YOUR view with reasoning. Panels respect nuanced opinions, not extreme positions.', difficulty: 'hard', sort_order: 17 },
    { category: 'GK', question_text: 'Name 3 government schemes launched in the last year. Explain any one.', model_answer: 'Pick schemes you actually understand. For each: name, ministry, objective, target group. For the detailed one, add: budget allocation, implementation status, criticism if any. Shows you follow policy, not just news.', difficulty: 'medium', sort_order: 18 },
    { category: 'GK', question_text: 'What is the difference between fiscal policy and monetary policy? Give an example of each from recent news.', model_answer: 'Fiscal = government (taxes, spending, budget). Monetary = RBI (interest rates, repo rate, CRR). Example: "The FM reduced income tax slabs (fiscal). RBI kept repo rate unchanged at 6.5% to control inflation (monetary)." Connect to current context.', difficulty: 'medium', sort_order: 19 },
    { category: 'GK', question_text: 'Who is the current RBI Governor? What is the repo rate right now and why does it matter?', model_answer: 'State the name and repo rate (verify latest). Explain simply: "Repo rate is the rate at which RBI lends to banks. When it\'s high, loans become expensive, people borrow less, and inflation cools. When low, borrowing increases and economy grows faster."', difficulty: 'easy', sort_order: 20 },
    { category: 'GK', question_text: 'What is the Russia-Ukraine war about? How does it affect India?', model_answer: 'Brief context: NATO expansion, Crimea annexation, Feb 2022 invasion. India impact: crude oil prices, defense imports, diplomatic balancing (abstaining at UN), rupee-ruble trade. Show geopolitical awareness.', difficulty: 'hard', sort_order: 21 },
    { category: 'Situational', question_text: 'Tell me about a time you failed. What did you learn?', model_answer: 'Pick a REAL failure (not a humble brag like "I worked too hard"). Describe what happened, why it went wrong, what you did after, and specifically how you changed. E.g., "I promised to deliver a school magazine in 2 weeks, underestimated the printing timeline, and missed the deadline by 5 days. I learned to always add buffer time and communicate delays early."', difficulty: 'medium', sort_order: 22 },
    { category: 'Situational', question_text: 'You\'re leading a team of 5 for a college project. Two members aren\'t contributing. What do you do?', model_answer: 'Show leadership + empathy. Step 1: Understand WHY they\'re not contributing (personal issues? lack of interest? unclear roles?). Step 2: Redistribute work based on strengths. Step 3: Set clear deadlines with accountability. Step 4: If still not working, escalate honestly but fairly. Never say "I\'d do their work myself."', difficulty: 'medium', sort_order: 23 },
    { category: 'Situational', question_text: 'Your best friend asks you to help them cheat in an exam. What do you do?', model_answer: 'This tests integrity. Be clear: "I wouldn\'t help them cheat." But show empathy: "I\'d offer to help them study, share my notes, or find them a tutor. I\'d explain that cheating hurts them more than it helps." Don\'t be preachy — be human.', difficulty: 'easy', sort_order: 24 },
    { category: 'Situational', question_text: 'If you don\'t get into any IIM, what is your Plan B?', model_answer: 'Show you\'ve thought about this maturely. Have a genuine backup: "I\'d take a gap year and reappear, while also preparing for CAT / CLAT / studying abroad." Or: "I\'d join [specific college] and build my profile for MBA later." Never say "I haven\'t thought about it" or "I only want IIM."', difficulty: 'medium', sort_order: 25 },
    { category: 'Situational', question_text: 'Your parents want you to do engineering but you want IPM. How did you convince them?', model_answer: 'Show the process: "I researched IIM Indore placement data, showed them the ROI comparison (5 years IPM vs 4+2 years BTech+MBA), arranged a call with an alumni, and addressed their concerns about security." Be respectful about parents — never criticize them.', difficulty: 'easy', sort_order: 26 },
    { category: 'Situational', question_text: 'You discover your company is doing something unethical but profitable. What do you do?', model_answer: 'Show ethical reasoning: "I\'d first verify the facts independently. Then raise it internally through proper channels. If ignored, I\'d escalate to compliance or whistleblower mechanisms." Show you understand the complexity — it\'s not always black and white.', difficulty: 'hard', sort_order: 27 },
    { category: 'Situational', question_text: 'What is your biggest weakness? How are you working on it?', model_answer: 'Pick a REAL weakness (not "I\'m a perfectionist"). Be specific and show active improvement. E.g., "I tend to procrastinate on tasks I find boring. I\'ve started using the Pomodoro technique and breaking large tasks into smaller milestones — my Class 12 prep was much more organized because of this."', difficulty: 'medium', sort_order: 28 },
    { category: 'Why IIM', question_text: 'Why IIM Indore specifically? Not IIM Ahmedabad or Bangalore?', model_answer: 'Focus on what\'s UNIQUE to IIM Indore: the 5-year IPM program structure, Indore campus, specific faculty research, clubs, exchange programs. Mention something specific: "I know Prof. X\'s work on behavioral economics" or "The Udan festival combines management and culture."', difficulty: 'hard', sort_order: 29 },
    { category: 'Why IIM', question_text: 'What do you know about the IPM curriculum? What excites you most?', model_answer: 'Show you\'ve done homework. Mention: the 3+2 structure (3 years undergrad + 2 years MBA), foundation courses in Year 1-3 (economics, sociology, math, humanities), electives in Year 4-5, summer internships, exchange programs. Pick a specific course/area that excites you and explain why.', difficulty: 'medium', sort_order: 30 },
    { category: 'Why IIM', question_text: 'What will you contribute to IIM Indore that other candidates won\'t?', model_answer: 'This is YOUR unique value proposition. Think about: your city\'s perspective, your unique hobby/skill, your extracurricular, your professional exposure through parents, your cultural background. Be specific: "I can bring my experience in competitive quiz — I\'ll contribute to the Quiz Club and help organize inter-IIM quiz events."', difficulty: 'hard', sort_order: 31 },
    { category: 'Why IIM', question_text: 'IPM is 5 years. What if you realize MBA isn\'t for you after Year 2?', model_answer: 'Show you\'ve considered this: "The first 3 years give me a broad foundation including humanities and social sciences — even if I pivot, those skills are valuable. But I\'ve chosen IPM deliberately after exploring other options, so I\'m confident this is the right path. The 5-year structure actually gives me time to explore before specializing."', difficulty: 'medium', sort_order: 32 },
    { category: 'Why IIM', question_text: 'Do you know the fees for the IPM program? Is it worth it?', model_answer: 'Know the number (currently ~₹30-35 lakhs for 5 years). Then build the ROI case: average placement package, loan options, scholarship possibilities. Compare with alternatives (4 years BTech + 2 years MBA = higher total cost + more time). Show financial maturity.', difficulty: 'easy', sort_order: 33 },
    { category: 'SOP', question_text: 'If I read your SOP to your best friend, would they say it sounds like you?', model_answer: 'This checks authenticity. Be honest: "My friend would recognize my career goal but might say my intro is more formal than how I actually talk. I tried to balance authenticity with professionalism." Shows self-awareness.', difficulty: 'medium', sort_order: 34 },
    { category: 'SOP', question_text: 'What is the one thing in your SOP that you\'re most proud of?', model_answer: 'Pick something genuine — a real achievement, a moment of growth, or a decision you made. Don\'t pick "I wrote a great SOP." Pick "I\'m proud that I mentioned my failure with [X] because it took courage to be honest about it in an interview context."', difficulty: 'easy', sort_order: 35 },
    { category: 'GK', question_text: 'What is your opinion on AI replacing jobs in India?', model_answer: 'Show nuance. "AI will automate repetitive tasks but create new roles we can\'t imagine yet. The risk is inequality — English-speaking, tech-savvy urban youth will benefit while rural workers may suffer. India needs to invest in reskilling. For management graduates, AI is an opportunity — understanding AI strategy will be a competitive advantage."', difficulty: 'hard', sort_order: 36 },
    { category: 'GK', question_text: 'Name the Finance Minister, Home Minister, and Education Minister of India.', model_answer: 'Factual question — you MUST know this. Also know: Chief Justice of India, RBI Governor, SEBI Chairman, WHO head, UN Secretary General. These are basic PI facts. Getting these wrong is a red flag.', difficulty: 'easy', sort_order: 37 },
    { category: 'GK', question_text: 'What is the National Education Policy 2020? How does it affect you?', model_answer: 'Key points: 5+3+3+4 structure, multidisciplinary approach, mother tongue instruction, academic credit bank, 4-year UG degree option. Personal impact: "NEP encourages integrated programs like IPM — the policy recognizes that management education shouldn\'t be limited to postgraduates."', difficulty: 'medium', sort_order: 38 },
    { category: 'Situational', question_text: 'If you had ₹10 lakhs right now, how would you invest it?', model_answer: 'Show financial awareness. Don\'t say "save it all" or "spend it all." Diversify: "₹4L in mutual funds (SIP for long-term growth), ₹2L in fixed deposits (emergency fund), ₹2L in a skill development course or business idea, ₹2L for education loans repayment or travel for learning." Explain your reasoning.', difficulty: 'medium', sort_order: 39 },
    { category: 'Situational', question_text: 'Describe a day in your life 10 years from now.', model_answer: 'Be vivid but realistic. Show ambition + work-life balance. "I wake up at 6 AM, review my team\'s quarterly targets, have a strategy meeting at 9, mentor a new hire at lunch, work on a client presentation in the afternoon, leave by 7 PM to spend time with family, and read for 30 minutes before bed." Make it specific to your career goal.', difficulty: 'easy', sort_order: 40 },
  ];

  // ── SESSIONS ──
  const sessions = [
    { session_type: 'recorded', title: 'How to Crack the IIM Indore PI — Complete Strategy', speaker: 'Vivek Sharma', session_date: '2026-03-15', duration: '45 min', youtube_id: '', tags: ['Strategy', 'PI Tips'], description: 'Full breakdown of the IIM Indore PI process — what panels look for, common mistakes, and how to structure your answers.', is_published: true },
    { session_type: 'recorded', title: 'SOP Masterclass — How to Write an SOP That Survives Cross-Questioning', speaker: 'Vivek Sharma', session_date: '2026-03-22', duration: '38 min', youtube_id: '', tags: ['SOP', 'Writing'], description: "Step-by-step guide to writing an SOP that the panel can't poke holes in. With live examples and rewrites.", is_published: true },
    { session_type: 'recorded', title: 'Current Affairs Rapid Fire — Top 30 GK Questions for PI', speaker: 'Vivek Sharma', session_date: '2026-04-01', duration: '30 min', youtube_id: '', tags: ['GK', 'Current Affairs'], description: "Quick-fire session covering the 30 most likely current affairs questions you'll face in your PI.", is_published: true },
    { session_type: 'recorded', title: 'Mock PI Live — Watch a Real Student Get Grilled', speaker: 'Vivek Sharma', session_date: '2026-04-10', duration: '55 min', youtube_id: '', tags: ['Mock PI', 'Live Demo'], description: "Live mock PI with a real IPMAT student. Panel asks tough questions, student answers, expert breaks down what worked and what didn't.", is_published: true },
    { session_type: 'live', title: 'Body Language & Confidence Hacks for PI Day', speaker: 'Vivek Sharma', session_date: '2026-04-28', session_time: '6:00 PM IST', duration: '40 min', youtube_link: '', tags: ['Soft Skills', 'Confidence'], description: 'Non-verbal cues that make or break your PI. How to sit, where to look, when to smile, and how to handle awkward silences.', is_published: true },
    { session_type: 'live', title: 'Live Mock PI — Open Slots for 3 Students', speaker: 'Vivek Sharma', session_date: '2026-05-03', session_time: '5:00 PM IST', duration: '60 min', youtube_link: '', tags: ['Mock PI', 'Interactive'], description: "Live mock PI on YouTube. 3 students will be selected to face the panel live — submit your name to participate!", is_published: true },
    { session_type: 'live', title: 'Last-Minute PI Checklist — 48 Hours Before Your Interview', speaker: 'Vivek Sharma', session_date: '2026-05-10', session_time: '7:00 PM IST', duration: '35 min', youtube_link: '', tags: ['Strategy', 'Last Minute'], description: 'Everything you need to do in the final 48 hours. Document checklist, revision plan, sleep schedule, and mental preparation.', is_published: true },
  ];

  // ── EXPERTS ──
  const experts = [
    { name: 'Vivek Sharma', title: 'Founder & Lead PI Coach', bio: 'IIM Indore IPM alumnus. 5+ years coaching IPMAT aspirants. Has trained 200+ students who cracked IPM interviews. Specializes in SOP strategy, mock PI, and confidence building.', specialties: ['Full Mock PI', 'SOP Review', 'Career Guidance'], rating: 4.9, sessions_count: 350, price: 499, slots: { Mon: ['4:00 PM', '5:00 PM', '6:00 PM'], Wed: ['4:00 PM', '5:00 PM', '6:00 PM'], Fri: ['4:00 PM', '5:00 PM'], Sat: ['10:00 AM', '11:00 AM', '12:00 PM', '2:00 PM'] }, phone: '918299470392', is_active: true },
    { name: 'Priya Mehta', title: 'PI Strategy Expert', bio: 'MBA from IIM Lucknow. Former corporate recruiter turned PI coach. Expert at turning average profiles into compelling stories. Known for her "Story-First" SOP approach.', specialties: ['SOP Deep-Dive', 'Profile Building', 'HR Questions'], rating: 4.8, sessions_count: 210, price: 399, slots: { Tue: ['4:00 PM', '5:00 PM', '6:00 PM'], Thu: ['4:00 PM', '5:00 PM', '6:00 PM'], Sat: ['3:00 PM', '4:00 PM', '5:00 PM'] }, phone: '918299470392', is_active: true },
    { name: 'Arjun Kapoor', title: 'GK & Current Affairs Coach', bio: 'UPSC prelims cleared. Deep expertise in current affairs, economics, and polity. Prepares students for the GK grilling that trips most IPM candidates.', specialties: ['Current Affairs', 'GK Prep', 'Opinion Questions'], rating: 4.7, sessions_count: 180, price: 349, slots: { Mon: ['5:00 PM', '6:00 PM', '7:00 PM'], Wed: ['5:00 PM', '6:00 PM', '7:00 PM'], Fri: ['5:00 PM', '6:00 PM'] }, phone: '918299470392', is_active: true },
  ];

  try {
    // Insert questions
    const allQs = questions.map(q => ({ ...q, is_published: true }));
    const { data: qData, error: qErr } = await supabase.from('pi_questions').insert(allQs).select('id');
    if (qErr) results.errors.push('questions: ' + qErr.message);
    else results.questions = qData.length;

    // Insert sessions
    const { data: sData, error: sErr } = await supabase.from('pi_sessions').insert(sessions).select('id');
    if (sErr) results.errors.push('sessions: ' + sErr.message);
    else results.sessions = sData.length;

    // Insert experts
    const { data: eData, error: eErr } = await supabase.from('pi_experts').insert(experts).select('id');
    if (eErr) results.errors.push('experts: ' + eErr.message);
    else results.experts = eData.length;
  } catch (err) {
    results.errors.push('general: ' + err.message);
  }

  return res.status(200).json(results);
}
