// /pages/api/seed-pi-data.js — ONE-TIME seed script. DELETE AFTER USE.
import { getSupabaseServer } from "../../utils/supabaseClient";

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "POST only" });

  const { secret, action } = req.body;
  if (secret !== "seed2026ipm") return res.status(403).json({ error: "Bad secret" });

  const supabase = getSupabaseServer();

  // ACTION: cleanup — remove duplicate questions/experts from double-run
  if (action === "cleanup") {
    // Delete ALL seed questions (sort_order 1-40) and experts, then re-insert fresh
    const { error: qDel } = await supabase.from('pi_questions').delete().gte('sort_order', 1).lte('sort_order', 40);
    const { error: eDel } = await supabase.from('pi_experts').delete().in('name', ['Vivek Sharma', 'Priya Mehta', 'Arjun Kapoor']);
    return res.status(200).json({
      cleaned: true,
      qError: qDel?.message || null,
      eError: eDel?.message || null,
    });
  }

  // ACTION: seed sessions only (with correct session_type)
  if (action === "sessions") {
    const sessions = [
      { session_type: 'recorded', title: 'How to Crack the IIM Indore PI — Complete Strategy', speaker: 'Vivek Sharma', session_date: '2026-03-15', duration: '45 min', youtube_id: '', tags: ['Strategy', 'PI Tips'], description: 'Full breakdown of the IIM Indore PI process — what panels look for, common mistakes, and how to structure your answers.', is_published: true },
      { session_type: 'recorded', title: 'SOP Masterclass — How to Write an SOP That Survives Cross-Questioning', speaker: 'Vivek Sharma', session_date: '2026-03-22', duration: '38 min', youtube_id: '', tags: ['SOP', 'Writing'], description: "Step-by-step guide to writing an SOP that the panel can't poke holes in. With live examples and rewrites.", is_published: true },
      { session_type: 'recorded', title: 'Current Affairs Rapid Fire — Top 30 GK Questions for PI', speaker: 'Vivek Sharma', session_date: '2026-04-01', duration: '30 min', youtube_id: '', tags: ['GK', 'Current Affairs'], description: "Quick-fire session covering the 30 most likely current affairs questions you'll face in your PI.", is_published: true },
      { session_type: 'recorded', title: 'Mock PI Live — Watch a Real Student Get Grilled', speaker: 'Vivek Sharma', session_date: '2026-04-10', duration: '55 min', youtube_id: '', tags: ['Mock PI', 'Live Demo'], description: "Live mock PI with a real IPMAT student. Panel asks tough questions, student answers, expert breaks down what worked and what didn't.", is_published: true },
      { session_type: 'upcoming', title: 'Body Language & Confidence Hacks for PI Day', speaker: 'Vivek Sharma', session_date: '2026-04-28', session_time: '6:00 PM IST', duration: '40 min', youtube_link: '', tags: ['Soft Skills', 'Confidence'], description: 'Non-verbal cues that make or break your PI. How to sit, where to look, when to smile, and how to handle awkward silences.', is_published: true },
      { session_type: 'upcoming', title: 'Live Mock PI — Open Slots for 3 Students', speaker: 'Vivek Sharma', session_date: '2026-05-03', session_time: '5:00 PM IST', duration: '60 min', youtube_link: '', tags: ['Mock PI', 'Interactive'], description: "Live mock PI on YouTube. 3 students will be selected to face the panel live — submit your name to participate!", is_published: true },
      { session_type: 'upcoming', title: 'Last-Minute PI Checklist — 48 Hours Before Your Interview', speaker: 'Vivek Sharma', session_date: '2026-05-10', session_time: '7:00 PM IST', duration: '35 min', youtube_link: '', tags: ['Strategy', 'Last Minute'], description: 'Everything you need to do in the final 48 hours. Document checklist, revision plan, sleep schedule, and mental preparation.', is_published: true },
    ];

    const { data, error } = await supabase.from('pi_sessions').insert(sessions).select('id');
    return res.status(200).json({ sessions: data?.length || 0, error: error?.message || null });
  }

  // ACTION: seed questions + experts
  if (action === "qe") {
    const questions = [
      { category: 'SOP', question_text: 'Walk us through your SOP. What is the central theme?', model_answer: 'Pick the ONE core thread that connects your intro, why-MBA, and career goals. Don\'t just summarize — highlight the "red thread." E.g., "My SOP is built around the idea that exposure to diverse perspectives drives better decisions — which is why I want IPM\'s 5-year integrated structure."', difficulty: 'medium', sort_order: 1, is_published: true },
      { category: 'SOP', question_text: 'You mentioned [specific strength] in your SOP. Give me a concrete example where this strength was tested.', model_answer: 'Use the STAR method: Situation → Task → Action → Result. Be specific with numbers and outcomes. If you wrote "leadership," don\'t just say "I led my team" — say "I led a 12-member debate team, increased participation by 40%, and we reached nationals for the first time in 5 years."', difficulty: 'hard', sort_order: 2, is_published: true },
      { category: 'SOP', question_text: 'Your SOP says you want to be [career goal]. What specifically will you do in Year 1 vs Year 5 vs Year 10?', model_answer: 'Show a clear progression. Year 1: Learn fundamentals, get exposure. Year 5: Mid-level role with specific responsibilities. Year 10: Leadership role or entrepreneurship. Be realistic — don\'t say "CEO of Google" but also don\'t be vague. Connect each stage back to skills IPM will give you.', difficulty: 'hard', sort_order: 3, is_published: true },
      { category: 'SOP', question_text: 'If we reject your SOP and ask you to rewrite it in 5 minutes, what would you change?', model_answer: 'This tests self-awareness. Acknowledge one genuine weakness (e.g., "I\'d add more specific data to support my claims" or "I\'d make my career goal more concrete"). Never say "nothing" — that shows lack of reflection.', difficulty: 'hard', sort_order: 4, is_published: true },
      { category: 'SOP', question_text: 'You wrote that IIM Indore is your dream college. What if you also get IIM Rohtak or NALSAR?', model_answer: 'Show you\'ve researched IIM Indore specifically — mention the 5-year integrated structure, Indore campus, specific clubs/fests, faculty, or alumni you\'ve looked up. Then honestly discuss how you\'d decide, showing mature thinking.', difficulty: 'medium', sort_order: 5, is_published: true },
      { category: 'SOP', question_text: 'What is the biggest risk in your career plan?', model_answer: 'Show you\'ve thought about what could go wrong. E.g., "The consulting industry is evolving with AI — my risk is that traditional strategy roles may shrink. That\'s why I want to combine management with tech skills during IPM." Shows maturity.', difficulty: 'medium', sort_order: 6, is_published: true },
      { category: 'SOP', question_text: 'Your SOP mentions [extracurricular]. What did you learn from it that is NOT obvious?', model_answer: 'Go beyond surface learning. If you played cricket, don\'t just say "teamwork." Say "I learned that the best captain isn\'t the best player — it\'s the one who makes others perform. I once dropped our top batsman from a match because his attitude was toxic, and we still won."', difficulty: 'medium', sort_order: 7, is_published: true },
      { category: 'SOP', question_text: 'Tell me something about yourself that is NOT in your SOP or application.', model_answer: 'This is a gift question — use it to show personality. Share something interesting: a hobby, a belief, a childhood story, a skill. Make it memorable. "I collect vintage maps" is better than "I\'m hardworking."', difficulty: 'easy', sort_order: 8, is_published: true },
      { category: 'Academics', question_text: 'Why did your score drop/improve between Class 10 and Class 12?', model_answer: 'Be honest. If it dropped: acknowledge it, explain what happened (e.g., health, new subjects, overconfidence), and what you learned. If it improved: explain what changed in your approach. Never blame teachers or the system — take ownership.', difficulty: 'medium', sort_order: 9, is_published: true },
      { category: 'Academics', question_text: 'What is your favorite subject and why? Teach me something from it in 2 minutes.', model_answer: 'Pick a subject you genuinely enjoy. Then TEACH — don\'t just describe. E.g., "I love Economics. Let me explain the paradox of thrift: when everyone saves more during a recession, total savings actually decrease because spending drops, businesses suffer, and incomes fall."', difficulty: 'medium', sort_order: 10, is_published: true },
      { category: 'Academics', question_text: 'You scored X in IPMAT. What was your preparation strategy?', model_answer: 'Be specific: how many months, daily routine, resources used, weak areas, mock test scores, what you\'d do differently. Shows discipline and self-awareness.', difficulty: 'easy', sort_order: 11, is_published: true },
      { category: 'Academics', question_text: 'If you could remove one subject from your school curriculum, which one and why?', model_answer: 'This tests critical thinking, not the "right" answer. Pick any subject and build a logical argument. E.g., "I\'d restructure Social Studies to include financial literacy — knowing about the Mughal empire is useful but knowing about compound interest and taxes is immediately practical."', difficulty: 'medium', sort_order: 12, is_published: true },
      { category: 'Academics', question_text: 'Explain a concept from Mathematics/Physics that has a real-world application most people don\'t know about.', model_answer: 'Show depth. E.g., "Game Theory from Math is used by telecom companies to decide pricing — if Jio drops prices, Airtel has to decide whether to match or differentiate. The Nash Equilibrium explains why they often end up at similar prices."', difficulty: 'hard', sort_order: 13, is_published: true },
      { category: 'Academics', question_text: 'Why MBA at 18? Why not engineering or CA?', model_answer: 'Don\'t trash other careers. Instead, explain what specifically draws you to management: decision-making, working across functions, building organizations. Connect to a personal experience that made you realize this.', difficulty: 'hard', sort_order: 14, is_published: true },
      { category: 'GK', question_text: 'What is the current GDP growth rate of India? Is it good or bad?', model_answer: 'State the number (check latest RBI/IMF data). Then analyze: compare with last year, compare with China/US, discuss what\'s driving it. Show you can think beyond the number.', difficulty: 'medium', sort_order: 15, is_published: true },
      { category: 'GK', question_text: 'Explain the Union Budget in 3 sentences. What was the most important announcement?', model_answer: 'Keep it crisp. Cover: total expenditure, fiscal deficit target, and 1-2 key announcements relevant to education/youth. Show you actually read it, not just headlines.', difficulty: 'hard', sort_order: 16, is_published: true },
      { category: 'GK', question_text: 'Should India have a Uniform Civil Code? Give arguments for and against.', model_answer: 'This tests balanced thinking. FOR: equality, simplification, gender justice. AGAINST: diversity, federalism, religious freedom. Then state YOUR view with reasoning. Panels respect nuanced opinions.', difficulty: 'hard', sort_order: 17, is_published: true },
      { category: 'GK', question_text: 'Name 3 government schemes launched in the last year. Explain any one.', model_answer: 'Pick schemes you actually understand. For each: name, ministry, objective, target group. For the detailed one, add: budget allocation, implementation status, criticism if any.', difficulty: 'medium', sort_order: 18, is_published: true },
      { category: 'GK', question_text: 'What is the difference between fiscal policy and monetary policy? Give an example of each from recent news.', model_answer: 'Fiscal = government (taxes, spending, budget). Monetary = RBI (interest rates, repo rate, CRR). Connect to current context with real examples.', difficulty: 'medium', sort_order: 19, is_published: true },
      { category: 'GK', question_text: 'Who is the current RBI Governor? What is the repo rate right now and why does it matter?', model_answer: 'State the name and repo rate (verify latest). Explain: "Repo rate is the rate at which RBI lends to banks. When high, loans become expensive, people borrow less, inflation cools."', difficulty: 'easy', sort_order: 20, is_published: true },
      { category: 'GK', question_text: 'What is the Russia-Ukraine war about? How does it affect India?', model_answer: 'Brief context: NATO expansion, Crimea, Feb 2022 invasion. India impact: crude oil prices, defense imports, diplomatic balancing, rupee-ruble trade.', difficulty: 'hard', sort_order: 21, is_published: true },
      { category: 'Situational', question_text: 'Tell me about a time you failed. What did you learn?', model_answer: 'Pick a REAL failure (not a humble brag). Describe what happened, why it went wrong, what you did after, and specifically how you changed.', difficulty: 'medium', sort_order: 22, is_published: true },
      { category: 'Situational', question_text: 'You\'re leading a team of 5 for a college project. Two members aren\'t contributing. What do you do?', model_answer: 'Show leadership + empathy. Understand WHY, redistribute work, set clear deadlines with accountability. Never say "I\'d do their work myself."', difficulty: 'medium', sort_order: 23, is_published: true },
      { category: 'Situational', question_text: 'Your best friend asks you to help them cheat in an exam. What do you do?', model_answer: 'This tests integrity. Be clear: "I wouldn\'t help them cheat." But show empathy: offer to help them study, share notes. Don\'t be preachy — be human.', difficulty: 'easy', sort_order: 24, is_published: true },
      { category: 'Situational', question_text: 'If you don\'t get into any IIM, what is your Plan B?', model_answer: 'Show you\'ve thought about this maturely. Have a genuine backup. Never say "I haven\'t thought about it" or "I only want IIM."', difficulty: 'medium', sort_order: 25, is_published: true },
      { category: 'Situational', question_text: 'Your parents want you to do engineering but you want IPM. How did you convince them?', model_answer: 'Show the process: research, ROI comparison, alumni call. Be respectful about parents — never criticize them.', difficulty: 'easy', sort_order: 26, is_published: true },
      { category: 'Situational', question_text: 'You discover your company is doing something unethical but profitable. What do you do?', model_answer: 'Show ethical reasoning: verify facts, raise internally, escalate if ignored. Show you understand the complexity.', difficulty: 'hard', sort_order: 27, is_published: true },
      { category: 'Situational', question_text: 'What is your biggest weakness? How are you working on it?', model_answer: 'Pick a REAL weakness (not "I\'m a perfectionist"). Be specific and show active improvement with concrete steps.', difficulty: 'medium', sort_order: 28, is_published: true },
      { category: 'Why IIM', question_text: 'Why IIM Indore specifically? Not IIM Ahmedabad or Bangalore?', model_answer: 'Focus on what\'s UNIQUE to IIM Indore: the 5-year IPM program, Indore campus, specific faculty, clubs, exchange programs. Be specific.', difficulty: 'hard', sort_order: 29, is_published: true },
      { category: 'Why IIM', question_text: 'What do you know about the IPM curriculum? What excites you most?', model_answer: 'Mention the 3+2 structure, foundation courses, electives, internships, exchange programs. Pick a specific area that excites you.', difficulty: 'medium', sort_order: 30, is_published: true },
      { category: 'Why IIM', question_text: 'What will you contribute to IIM Indore that other candidates won\'t?', model_answer: 'Your unique value proposition: city perspective, unique hobby/skill, extracurricular, cultural background. Be specific.', difficulty: 'hard', sort_order: 31, is_published: true },
      { category: 'Why IIM', question_text: 'IPM is 5 years. What if you realize MBA isn\'t for you after Year 2?', model_answer: 'Show you\'ve considered this. The first 3 years give a broad foundation. You\'ve chosen IPM deliberately after exploring other options.', difficulty: 'medium', sort_order: 32, is_published: true },
      { category: 'Why IIM', question_text: 'Do you know the fees for the IPM program? Is it worth it?', model_answer: 'Know the number (~30-35 lakhs for 5 years). Build the ROI case: placement packages, loan options, comparison with BTech+MBA. Show financial maturity.', difficulty: 'easy', sort_order: 33, is_published: true },
      { category: 'SOP', question_text: 'If I read your SOP to your best friend, would they say it sounds like you?', model_answer: 'This checks authenticity. Be honest about the balance between your natural voice and professional tone. Shows self-awareness.', difficulty: 'medium', sort_order: 34, is_published: true },
      { category: 'SOP', question_text: 'What is the one thing in your SOP that you\'re most proud of?', model_answer: 'Pick something genuine — a real achievement, a moment of growth, or a decision you made. Don\'t pick "I wrote a great SOP."', difficulty: 'easy', sort_order: 35, is_published: true },
      { category: 'GK', question_text: 'What is your opinion on AI replacing jobs in India?', model_answer: 'Show nuance. AI will automate repetitive tasks but create new roles. Risk is inequality. India needs reskilling. For management graduates, AI is an opportunity.', difficulty: 'hard', sort_order: 36, is_published: true },
      { category: 'GK', question_text: 'Name the Finance Minister, Home Minister, and Education Minister of India.', model_answer: 'Factual question — you MUST know this. Also know: CJI, RBI Governor, SEBI Chairman, WHO head, UN Secretary General. Getting these wrong is a red flag.', difficulty: 'easy', sort_order: 37, is_published: true },
      { category: 'GK', question_text: 'What is the National Education Policy 2020? How does it affect you?', model_answer: 'Key points: 5+3+3+4 structure, multidisciplinary approach, mother tongue instruction, academic credit bank, 4-year UG degree option.', difficulty: 'medium', sort_order: 38, is_published: true },
      { category: 'Situational', question_text: 'If you had 10 lakhs right now, how would you invest it?', model_answer: 'Show financial awareness. Diversify across mutual funds, FDs, skill development, and education. Explain your reasoning.', difficulty: 'medium', sort_order: 39, is_published: true },
      { category: 'Situational', question_text: 'Describe a day in your life 10 years from now.', model_answer: 'Be vivid but realistic. Show ambition + work-life balance. Make it specific to your career goal.', difficulty: 'easy', sort_order: 40, is_published: true },
    ];

    const experts = [
      { name: 'Vivek Sharma', title: 'Founder & Lead PI Coach', bio: 'IIM Indore IPM alumnus. 5+ years coaching IPMAT aspirants. Has trained 200+ students who cracked IPM interviews. Specializes in SOP strategy, mock PI, and confidence building.', specialties: ['Full Mock PI', 'SOP Review', 'Career Guidance'], rating: 4.9, sessions_count: 350, price: 499, slots: { Mon: ['4:00 PM', '5:00 PM', '6:00 PM'], Wed: ['4:00 PM', '5:00 PM', '6:00 PM'], Fri: ['4:00 PM', '5:00 PM'], Sat: ['10:00 AM', '11:00 AM', '12:00 PM', '2:00 PM'] }, phone: '918299470392', is_active: true },
      { name: 'Priya Mehta', title: 'PI Strategy Expert', bio: 'MBA from IIM Lucknow. Former corporate recruiter turned PI coach. Expert at turning average profiles into compelling stories. Known for her "Story-First" SOP approach.', specialties: ['SOP Deep-Dive', 'Profile Building', 'HR Questions'], rating: 4.8, sessions_count: 210, price: 399, slots: { Tue: ['4:00 PM', '5:00 PM', '6:00 PM'], Thu: ['4:00 PM', '5:00 PM', '6:00 PM'], Sat: ['3:00 PM', '4:00 PM', '5:00 PM'] }, phone: '918299470392', is_active: true },
      { name: 'Arjun Kapoor', title: 'GK & Current Affairs Coach', bio: 'UPSC prelims cleared. Deep expertise in current affairs, economics, and polity. Prepares students for the GK grilling that trips most IPM candidates.', specialties: ['Current Affairs', 'GK Prep', 'Opinion Questions'], rating: 4.7, sessions_count: 180, price: 349, slots: { Mon: ['5:00 PM', '6:00 PM', '7:00 PM'], Wed: ['5:00 PM', '6:00 PM', '7:00 PM'], Fri: ['5:00 PM', '6:00 PM'] }, phone: '918299470392', is_active: true },
    ];

    const r = {};
    const { data: qD, error: qE } = await supabase.from('pi_questions').insert(questions).select('id');
    r.questions = qD?.length || 0;
    if (qE) r.qError = qE.message;
    const { data: eD, error: eE } = await supabase.from('pi_experts').insert(experts).select('id');
    r.experts = eD?.length || 0;
    if (eE) r.eError = eE.message;
    return res.status(200).json(r);
  }

  return res.status(400).json({ error: "Specify action: cleanup, sessions, or qe" });
}
