// Only colleges that accept IPMAT Indore scores directly
export const collegesData = {
  "IIM Indore": {
    title: "IIM Indore",
    location: "Indore, Madhya Pradesh",
    picture: "/colleges/iim-indore.png",
    link: "https://cdn.digialm.com//EForms/configuredHtml/1329/97663/Registration.html",
    exam: "IPMAT Indore",
    lastDate: "14th March'2026",
    status: "CLOSED",
  },
  "IIM Ranchi": {
    title: "IIM Ranchi",
    location: "Ranchi, Jharkhand",
    picture: "/colleges/iim-ranchi.png",
    link: "https://app.iimranchi.ac.in/admission/ipm",
    exam: "IPMAT Indore",
    lastDate: "15th April'2026",
    status: "CLOSED",
  },
  "IIM Shillong": {
    title: "IIM Shillong",
    location: "Shillong, Meghalaya",
    picture: "/colleges/iim-shillong.png",
    link: null,
    exam: "IPMAT Indore",
    lastDate: "TBA",
    status: "UPCOMING",
  },
  "IIM Sirmaur": {
    title: "IIM Sirmaur",
    location: "Paonta Sahib, Himachal Pradesh",
    picture: "/colleges/iim-sirmaur.png",
    link: "https://iimsirmaur.iqdigit.com/register",
    exam: "IPMAT Indore (ATS)",
    lastDate: "30th April'2026",
    status: "CLOSED",
  },
  "IIM Amritsar": {
    title: "IIM Amritsar",
    location: "Amritsar, Punjab",
    picture: "/colleges/iim-amritsar.png",
    link: "https://admission.iimamritsar.ac.in/apply-register-non-mba",
    exam: "IPMAT Indore (ATS)",
    lastDate: "25th May'2026",
    status: "OPEN",
  },
  NIRMA: {
    title: "Nirma University",
    location: "Ahmedabad, Gujarat",
    picture:
      "https://nirmawebsite.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/07/Homepage-NU-950x732.jpg",
    link: "https://admissions-im.nirmauni.ac.in/student/default.aspx",
    exam: "IPMAT Indore",
    lastDate: "15th June'2026",
    status: "OPEN",
  },
  IIFT: {
    title: "IIFT Kakinada",
    location: "Kakinada, Andhra Pradesh",
    picture:
      "https://images.collegedunia.com/public/college_data/images/appImage/25453_IIFTD_NEW.jpg",
    link: "https://applyadmission.net/iift2026ipm/",
    exam: "IPMAT Indore",
    lastDate: "20th May'2026",
    status: "OPEN",
  },
  NALSAR: {
    title: "NALSAR University",
    location: "Hyderabad, Telangana",
    picture:
      "https://www.indcareer.com/files/notices/2015-03/nalsar-university-law-hyderabad.jpg",
    link: "https://apply.nalsar.ac.in/ipm-application-form",
    exam: "IPMAT Indore",
    lastDate: "10th May'2026",
    status: "OPEN",
  },
  TAPMI: {
    title: "TAPMI Manipal",
    location: "Manipal/Bengaluru, Karnataka",
    picture: "/colleges/tapmi-manipal.png",
    link: "https://apply.manipal.edu/login",
    exam: "IPMAT Indore + Others",
    lastDate: "30th May'2026",
    status: "OPEN",
  },
};
