// Only colleges that accept IPMAT Indore scores directly
// Last dates, links, and statuses synced from air1commandcenter (May 2026)
export const collegesData = {
  "IIM Indore": {
    title: "IIM Indore",
    location: "Indore, Madhya Pradesh",
    picture: "/colleges/iim-indore.png",
    link: "https://cdn.digialm.com//EForms/configuredHtml/1329/97663/Registration.html",
    exam: "IPMAT Indore",
    lastDate: "14th March '26",
    status: "CLOSED",
  },
  "IIM Ranchi": {
    title: "IIM Ranchi",
    location: "Ranchi, Jharkhand",
    picture: "/colleges/iim-ranchi.png",
    link: "https://app.iimranchi.ac.in/admission/ipm",
    exam: "IPMAT Indore",
    lastDate: "12th April '26",
    status: "CLOSED",
  },
  "IIM Shillong": {
    title: "IIM Shillong",
    location: "Shillong, Meghalaya",
    picture: "/colleges/iim-shillong.png",
    link: "https://apps.iimshillong.ac.in/admission/",
    exam: "IPMAT Indore",
    lastDate: "30th May '26",
    status: "OPEN",
  },
  "IIM Sirmaur": {
    title: "IIM Sirmaur",
    location: "Paonta Sahib, Himachal Pradesh",
    picture: "/colleges/iim-sirmaur.png",
    link: "https://iimsirmaur.iqdigit.com/register",
    exam: "IPMAT Indore (ATS)",
    lastDate: "15th March '26",
    status: "CLOSED",
  },
  "IIM Amritsar": {
    title: "IIM Amritsar",
    location: "Amritsar, Punjab",
    picture: "/colleges/iim-amritsar.png",
    link: "https://admission.iimamritsar.ac.in/apply-register-non-mba",
    exam: "IPMAT Indore (ATS)",
    lastDate: "31st March '26",
    status: "CLOSED",
  },
  "IIM Sambalpur": {
    title: "IIM Sambalpur",
    location: "Sambalpur, Odisha",
    picture: "/colleges/iim-sambalpur.png",
    link: "https://registration.iimsambalpur.ac.in/portal/SignIn/MPPolicy",
    exam: "IPMAT Indore",
    lastDate: "31st May '26",
    status: "OPEN",
  },
  NIRMA: {
    title: "Nirma University",
    location: "Ahmedabad, Gujarat",
    picture: "https://nirmawebsite.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/07/Homepage-NU-950x732.jpg",
    link: "https://admissions-im.nirmauni.ac.in/student/default.aspx",
    exam: "IPMAT Indore",
    lastDate: "10th May '26",
    status: "OPEN",
  },
  IIFT: {
    title: "IIFT Kakinada",
    location: "Kakinada, Andhra Pradesh",
    picture: "https://images.collegedunia.com/public/college_data/images/appImage/25453_IIFTD_NEW.jpg",
    link: "https://applyadmission.net/iift2026ipm/",
    exam: "IPMAT Indore",
    lastDate: "26th April '26",
    status: "CLOSED",
  },
  NALSAR: {
    title: "NALSAR University",
    location: "Hyderabad, Telangana",
    picture: "https://www.indcareer.com/files/notices/2015-03/nalsar-university-law-hyderabad.jpg",
    link: "https://apply.nalsar.ac.in/ipm-application-form",
    exam: "IPMAT Indore",
    lastDate: "31st May '26",
    status: "OPEN",
  },
  TAPMI: {
    title: "TAPMI Manipal",
    location: "Manipal/Bengaluru, Karnataka",
    picture: "/colleges/tapmi-manipal.png",
    link: "https://apply.manipal.edu/login?ec=302&startURL=%2F",
    exam: "IPMAT Indore + Others",
    lastDate: "2nd May '26",
    status: "CLOSED",
  },
  "Alliance University": {
    title: "Alliance University",
    location: "Bengaluru, Karnataka",
    picture: "/colleges/alliance.png",
    link: "https://apply.alliance.edu.in/undergraduate-application-form-2026?utm_source=IPMcareer&utm_medium=Kanpur&utm_campaign=BBA2026",
    exam: "IPMAT Indore",
    lastDate: "12th May '26",
    status: "OPEN",
  },
  "Krea University (IFMR)": {
    title: "Krea University (IFMR)",
    location: "Sri City, Andhra Pradesh",
    picture: "/colleges/krea.png",
    link: "https://ifmrgsbadmissions.krea.edu.in/ifmr-bba-programme-applynow",
    exam: "IPMAT Indore / KAT",
    lastDate: "10th June '26",
    status: "OPEN",
  },
  "LM Thapar (TIET)": {
    title: "LM Thapar (LMTSM)",
    location: "Patiala, Punjab",
    picture: "/colleges/thapar.png",
    link: null,
    exam: "IPMAT Indore + Others",
    lastDate: "TBA",
    status: "UPCOMING",
  },
  "NICMAR University": {
    title: "NICMAR University",
    location: "Pune, Maharashtra",
    picture: "/colleges/nicmar.png",
    link: null,
    exam: "IPMAT Indore / UG-NCAT",
    lastDate: "TBA",
    status: "UPCOMING",
  },
};
