export const collegesData = {
  "IIM Indore": {
    title: "IIM Indore",
    location: "Indore, Madhya Pradesh",
    picture: "/colleges/iim-indore.png",
    link: "https://cdn.digialm.com//EForms/configuredHtml/1329/97663/Registration.html",
    exam: "IPMAT Indore",
    lastDate: "14th March'2026",
    status: "CLOSED",
  },
  "IIM Rohtak": {
    title: "IIM Rohtak",
    location: "Rohtak, Haryana",
    picture: "/colleges/iim-rohtak.png",
    link: "https://cdn.digialm.com/EForms/configuredHtml/2349/97754/Registration.html",
    exam: "IPMAT Rohtak",
    lastDate: "06 April '2026",
    status: "CLOSED",
  },
  "IIM Ranchi": {
    title: "IIM Ranchi",
    location: "Ranchi, Jharkhand",
    picture: "/colleges/iim-ranchi.png",
    link: "https://app.iimranchi.ac.in/admission/ipm",
    exam: "IPMAT Ranchi",
    lastDate: "15th April'2026",
    status: "CLOSED",
  },
  "IIM Jammu": {
    title: "IIM Jammu",
    location: "Jammu, J&K",
    picture: "/colleges/iim-jammu.png",
    link: "https://examinationservices.nic.in/ExamSys26Part2/root/Home.aspx?enc=Ei4cajBkK1gZSfgr53ImFYIsjsAFC5allEdi8zWjhNlaMb/g70yJtxEs2NI2c8ln",
    exam: "JIPMAT",
    lastDate: "20th April'2026",
    status: "CLOSED",
  },
  "IIM Bodh Gaya": {
    title: "IIM Bodh Gaya",
    location: "Bodh Gaya, Bihar",
    picture: "/colleges/iim-bodhgaya.png",
    link: "https://examinationservices.nic.in/ExamSys26Part2/root/Home.aspx?enc=Ei4cajBkK1gZSfgr53ImFYIsjsAFC5allEdi8zWjhNlaMb/g70yJtxEs2NI2c8ln",
    exam: "JIPMAT",
    lastDate: "20th April'2026",
    status: "CLOSED",
  },
  "IIM Sirmaur": {
    title: "IIM Sirmaur",
    location: "Sirmaur, Himachal Pradesh",
    picture: "/colleges/iim-sirmaur.png",
    link: "https://iimsirmaur.iqdigit.com/register",
    exam: "IIM Sirmaur Entrance",
    lastDate: "30th April'2026",
    status: "CLOSED",
  },
  "IIM Sambalpur": {
    title: "IIM Sambalpur",
    location: "Sambalpur, Odisha",
    picture: "/colleges/iim-sambalpur.png",
    link: "https://registration.iimsambalpur.ac.in/portal/SignIn/MPPolicy",
    exam: "IPMAT Sambalpur",
    lastDate: "15th May'2026",
    status: "OPEN",
  },
  "IIM Shillong": {
    title: "IIM Shillong",
    location: "Shillong, Meghalaya",
    picture: "/colleges/iim-shillong.png",
    link: null,
    exam: "IIM Shillong Entrance",
    lastDate: "TBA",
    status: "UPCOMING",
  },
  "IIM Amritsar": {
    title: "IIM Amritsar",
    location: "Amritsar, Punjab",
    picture: "/colleges/iim-amritsar.png",
    link: "https://admission.iimamritsar.ac.in/apply-register-non-mba",
    exam: "IPMAT Amritsar",
    lastDate: "25th May'2026",
    status: "OPEN",
  },
  NALSAR: {
    title: "NALSAR University",
    location: "Hyderabad, Telangana",
    picture: "https://www.indcareer.com/files/notices/2015-03/nalsar-university-law-hyderabad.jpg",
    link: "https://apply.nalsar.ac.in/ipm-application-form",
    exam: "NALSAR IPM Entrance",
    lastDate: "10th May'2026",
    status: "OPEN",
  },
  IIFT: {
    title: "IIFT Kakinada",
    location: "Kakinada, Andhra Pradesh",
    picture: "https://images.collegedunia.com/public/college_data/images/appImage/25453_IIFTD_NEW.jpg",
    link: "https://applyadmission.net/iift2026ipm/",
    exam: "IIFT IPM Entrance",
    lastDate: "20th May'2026",
    status: "OPEN",
  },
  NIRMA: {
    title: "Nirma University",
    location: "Ahmedabad, Gujarat",
    picture: "https://nirmawebsite.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/07/Homepage-NU-950x732.jpg",
    link: "https://admissions-im.nirmauni.ac.in/student/default.aspx",
    exam: "Nirma BBA Entrance",
    lastDate: "15th June'2026",
    status: "OPEN",
  },
  TAPMI: {
    title: "TAPMI Manipal",
    location: "Manipal, Karnataka",
    picture: "/colleges/tapmi-manipal.png",
    link: "https://apply.manipal.edu/login",
    exam: "Manipal Entrance",
    lastDate: "30th May'2026",
    status: "OPEN",
  },
  "Christ University": {
    title: "Christ University",
    location: "Bangalore, Karnataka",
    picture: "/colleges/christ-university.png",
    link: "https://espro.christuniversity.in/Application/",
    exam: "Christ University Entrance",
    lastDate: "15th May'2026",
    status: "OPEN",
  },
  "Alliance University": {
    title: "Alliance University",
    location: "Bangalore, Karnataka",
    picture: "/colleges/alliance-university.png",
    link: "https://apply.alliance.edu.in/undergraduate-application-form-2026?utm_source=IPMcareer&utm_medium=Kanpur&utm_campaign=BBA2026",
    exam: "Alliance Entrance",
    lastDate: "20th June'2026",
    status: "OPEN",
  },
  "Krea University (IFMR)": {
    title: "Krea University (IFMR)",
    location: "Sri City, Andhra Pradesh",
    picture: "/colleges/krea-university.png",
    link: "https://ifmrgsbadmissions.krea.edu.in/ifmr-bba-programme-applynow?utm_source=IPM%20CAREER&utm_medium=Banner&utm_campaign=Kanpur&utm_content=header",
    exam: "Krea BBA Entrance",
    lastDate: "10th June'2026",
    status: "OPEN",
  },
  "LM Thapar (TIET)": {
    title: "LM Thapar School of Management",
    location: "Patiala, Punjab",
    picture: "/colleges/lm-thapar.png",
    link: null,
    exam: "Thapar Entrance",
    lastDate: "TBA",
    status: "UPCOMING",
  },
  "GLS University": {
    title: "GLS University",
    location: "Ahmedabad, Gujarat",
    picture: "/colleges/gls-university.png",
    link: null,
    exam: "GLS Entrance",
    lastDate: "TBA",
    status: "UPCOMING",
  },
  "NICMAR University": {
    title: "NICMAR University",
    location: "Pune, Maharashtra",
    picture: "/colleges/nicmar-university.png",
    link: null,
    exam: "NICMAR Entrance",
    lastDate: "TBA",
    status: "UPCOMING",
  },
};
